version: "3.8"

services:
  web:
    depends_on: 
      - api
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    volumes:
      - ./frontend:/app

  api: 
    depends_on: 
      - db
    build: ./backend
    ports: 
      - 3001:3001
    environment: 
      DB_URL: mongodb://db/vidly
    command: ./docker-entrypoint.sh
    volumes: 
      - ./backend:/app

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly: